services:
  - type: web
    name: sela-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python asgi_run.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: HUGGINGFACE_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
