services:
  - type: worker
    name: sela-bot-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: HUGGINGFACE_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: BSC_RPC_URL
        value: "https://bsc-dataseed.binance.org/"
      - key: SELA_TOKEN_ADDRESS  
        value: "0xACb0A09414CEA1C879c67bB7A877E4e19480f022"
      - key: BSC_CHAIN_ID
        value: "56"
